# ref link: https://alinex.gitlab.io/env/mkdocs/
#===================================================================================#
# Site Information
#===================================================================================#
site_name: Binbash Leverage Reference Architecture
repo_name: "binbashar/le-ref-architecture-doc"
repo_url: https://github.com/binbashar/le-ref-architecture-doc
site_url: https://leverage.binbash.com.ar/
site_description: Binbash Leverage Reference Architecture Documentation
site_author: Binbash
copyright: Copyright &copy; 2017-2021 <a href="https://www.binbash.com.ar">Binbash</a>

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  custom_dir: material
  language: en
  #logo: assets/images/logos/binbash-icon.png
  icon: # https://www.materialpalette.com/icons
    logo: material/book-open-page-variant

  favicon: assets/images/logos/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
  palette: # https://www.materialpalette.com/colors
    scheme: preference
    #primary: "teal" # comment to replace by /docs/assets/stylesheets
    accent: "deep purple"
  include_sidebar: true

extra:
  social:
    - icon: material/home
      link: 'https://www.binbash.com.ar'
    - icon: material/github
      link: 'https://github.com/binbashar'
    - icon: material/linkedin
      link: 'https://www.linkedin.com/company/binbash'
    - icon: material/slack
      link: 'https://join.slack.com/t/binbashar/shared_invite/zt-fw1692b6-9k4ADsWJ47lKacszphXM1w'
    - icon: fontawesome/brands/medium
      link: 'https://medium.com/binbash-inc'
    - icon: material/twitter
      link: 'https://twitter.com/binbash_devops'
    - icon: material/docker
      link: 'https://hub.docker.com/orgs/binbash'

#  alternate:
#
#    # Switch to English
#    - name: English
#      link: https://leverage.binbash.com.ar
#      lang: en
#
#    # Switch to Spanish
#    - name: Spanish
#      link: https://leverage.binbash.com.ar/es/
#      lang: es

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

plugins:
  - search
#  - awesome-pages

extra_css:
    - assets/stylesheets/extra.css

# Google Analytics (https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/)
#
google_analytics:
  - 'UA-172873342-1'
  - 'auto'

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home:
    - Home: "index.md"
    - Welcome: "welcome.md"
    - First steps: "first-steps/index.md"
    - How it works: "how-it-works/index.md"
    - User guide: "user-guide/index.md"
    - Work with us: "work-with-us/index.md"
    - License: "license.md"

  - First Steps:
    - Overview: "first-steps/index.md"

  - How it works:
    - Desing:
        - Overview: "how-it-works/index.md"
        - Why our stack?: "how-it-works/why.md"
        - Considerations: "how-it-works/considerations.md"
    - Leverage Code Library:
      - Overview: "how-it-works/code-library/code-library.md"
      - Specifications: "how-it-works/code-library/code-library-specs.md"
      - Modules per Tech: "how-it-works/code-library/modules-library-per-tech.md"
    - AWS Organization:
      - Organization: "how-it-works/organization/organization.md"
      - Accounts: "how-it-works/organization/accounts.md"
      - Billing: "how-it-works/organization/billing.md"
    - Identities:
      - Overview: "how-it-works/identities/identities.md"
      - IAM Roles: "how-it-works/identities/roles.md"
    - Security:
      - VPN: "how-it-works/security/vpn.md"
      - Services: "how-it-works/security/services.md"
    - Network:
      - VPC Topology: "how-it-works/network/vpc-topology.md"
      - VPC Adressing: "how-it-works/network/vpc-addressing.md"
      - VPC Peering: "how-it-works/network/vpc-peering.md"
      - DNS: "how-it-works/network/dns.md"
    - Compute:
      - Overview: "how-it-works/compute/overview.md"
      - K8s Kops: "how-it-works/compute/k8s-kops.md"
      - K8s EKS: "how-it-works/compute/k8s-eks.md"
      - Serverless: "how-it-works/compute/serverless.md"
    - Database:
       - Databases: "how-it-works/database/database.md"
       - MySQL: "how-it-works/database/mysql.md"
       - PostgresSQL: "how-it-works/database/postgres.md"
    - Storage: "how-it-works/storage/storage.md"
    - CDN: "how-it-works/cdn/cdn.md"
    - CI/CD: "how-it-works/ci-cd/ci-cd.md"
    - Tools: "how-it-works/tools/tools.md"
    - Monitoring:
      - Monitoring: "how-it-works/monitoring/monitoring.md"
      - Metrics: "how-it-works/monitoring/metrics.md"
      - Logs: "how-it-works/monitoring/logs.md"
      - Tracing: "how-it-works/monitoring/tracing.md"
      - APM: "how-it-works/monitoring/apm.md"
      - Notifications: "how-it-works/monitoring/notification_escalation.md"
    - Secrets: "how-it-works/secrets/secrets.md"
    - Reliability:
      - Backups: "how-it-works/reliability/backups.md"
      - High Availability: "how-it-works/reliability/high-availability.md"
      - Health Checks: "how-it-works/reliability/health-checks.md"
      - Disaster Recovery: "how-it-works/reliability/dr.md"
    - Costs: "how-it-works/costs/costs.md"
    - Read More: "how-it-works/read-more.md"

  - User guide:
    - Basic usage: "user-guide/index.md"
    - Configuration:
      - Overview: "user-guide/base-configuration/overview.md"
      - Repos:
        - Terraform Infra: "user-guide/base-configuration/repo-le-tf-infra-aws.md"
        - Ansible Infra: "user-guide/base-configuration/repo-le-ansible-infra.md"
        - Helm Infra: "user-guide/base-configuration/repo-le-helm-infra.md"
    - Workflow:
      - Repos:
        - Makefiles Lib: "user-guide/base-workflow/repo-le-dev-makefiles.md"
        - Terraform Infra: "user-guide/base-workflow/repo-le-tf-infra-aws.md"
        - Terraform Infra State: "user-guide/base-workflow/repo-le-tf-infra-aws-tf-state.md"
        - Ansible Infra: "user-guide/base-workflow/repo-le-ansible-infra.md"
        - Helm Infra: "user-guide/base-workflow/repo-le-helm-infra.md"
    - AWS Organization:
      - Organization: "user-guide/organization/organization.md"
    - Identities:
      - gpg: "user-guide/identities/gpg.md"
      - identities: "user-guide/identities/identities.md"
      - credentials: "user-guide/identities/credentials.md"
    - Security:
      - VPN: "user-guide/security/vpn.md"
      - Services: "user-guide/security/services.md"
    - Network:
      - VPC: "user-guide/network/vpc-addressing.md"
      - VPC Peering: "user-guide/network/vpc-peering.md"
      - DNS: "user-guide/network/dns.md"
    - Compute:
      - Overview: "user-guide/compute/overview.md"
      - K8s Kops: "user-guide/compute/k8s-kops.md"
      - K8s EKS: "user-guide/compute/k8s-eks.md"
      - Serverless: "user-guide/compute/serverless.md"
    - Database:
       - Databases: "user-guide/database/database.md"
       - MySQL: "user-guide/database/mysql.md"
       - PostgresSQL: "user-guide/database/postgres.md"
    - Storage: "user-guide/storage/storage.md"
    - CDN: "user-guide/cdn/cdn.md"
    - CI/CD: "user-guide/ci-cd/ci-cd.md"
    - Tools: "user-guide/tools/tools.md"
    - Monitoring:
      - Monitoring: "user-guide/monitoring/monitoring.md"
      - Metrics: "user-guide/monitoring/metrics.md"
      - Logs: "user-guide/monitoring/logs.md"
      - Tracing: "user-guide/monitoring/tracing.md"
      - APM: "user-guide/monitoring/apm.md"
    - Secrets: "user-guide/secrets/secrets.md"
    - Reliability:
      - Backups: "user-guide/reliability/backups.md"
      - Disaster Recovery: "user-guide/reliability/dr.md"
      - Health Checks: "user-guide/reliability/health-checks.md"
    - Costs: "user-guide/costs/costs.md"

  - Examples:
      - Introduction: "examples/index.md"
      - Prerequisites: "examples/PREREQUISITES.md"
      - AWS:
          - Organization: "examples/organization.md"
          - K8s Kops: "examples/k8s-kops.md"

  - Work with us:
      - Overview: "work-with-us/index.md"
      - Support:
          - Support: "work-with-us/support.md"
          - Updates:
              - January 2021: "work-with-us/updates/product-updates-01-2021.md"
      - Contribute: "work-with-us/contribute.md"
      - Roadmap:
        - Overview: "work-with-us/roadmap/overview.md"
        - Operational Excellence: "work-with-us/roadmap/operational-excellence.md"
        - Reliability & Performance: "work-with-us/roadmap/reliability-performance.md"
        - Security: "work-with-us/roadmap/security.md"
        - Cost Optimization: "work-with-us/roadmap/cost-optimization.md"
        - Demo Applications: "work-with-us/roadmap/demo-apps.md"
      - Careers: "work-with-us/careers.md"
      - FAQs: "work-with-us/faqs.md"
      - Contact: "work-with-us/contact.md"


